### ISSUE TITLE
Two clinical BERT repos?

### ISSUE THREAD

**Issue by sudarshan85** [kexinhuang12345/clinicalBERT#1]
Hi,

Is this repo from the same team as [this](https://github.com/EmilyAlsentzer/clinicalBERT) or are they completely different?

**Comment by kexinhuang12345** [comment]
Hi,

It is a different team, but a similar idea. if I am not mistaken, their checkpoints are in tensorflow and us in torch. So you could select by your favorite package. Let me know if you have further question!

**Comment by sudarshan85** [comment]
Thank you for your reply. In the paper it says "For pre-training ClinicalBert, we randomly sample 100,000 notes from mimic-iii.". Does this mean that the pre-trained weights that are available for download were trained on a random sample of 100,000 notes? Or do you have a BERT trained model that is trained on all of the MIMIC notes (over 2 million)?

**Comment by kexinhuang12345** [comment]
We only trained on 100,000 notes due to limited computational resource. But
we found it is already pretty good, since we started at the initial bert
checkpoint.

On Wed, May 15, 2019 at 10:15 AM sudarshan <notifications@github.com> wrote:

> Thank you for your reply. In the paper it says "For pre-training
> ClinicalBert, we randomly sample 100,000 notes from mimic-iii.". Does this
> mean that the pre-trained weights that are available for download were
> trained on a random sample of 100,000 notes? Or do you have a BERT trained
> model that is trained on all of the MIMIC notes (over 2 million)?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kexinhuang12345_clinicalBERT_issues_1-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAGUB5A55CBD4EACTUTAPWH3PVQLHXA5CNFSM4HMR5TM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVOZRGI-23issuecomment-2D492673177&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=pm9TebsFk47J6Yqy4-ntKg&m=6wGr7fQjBjyJMbhVxo7nV3zjJRcYmQ40_7oRPnNZ6m0&s=abdJX2Tno3uxFAK7ocojEZJjkod6-YPaw26x4GRQ-fk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGUB5AYRF5U4URKCF4PR5OLPVQLHXANCNFSM4HMR5TMQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=pm9TebsFk47J6Yqy4-ntKg&m=6wGr7fQjBjyJMbhVxo7nV3zjJRcYmQ40_7oRPnNZ6m0&s=FIjcSr2Gv91ODYvM2hm9t-EASDlkHKfIiSOxGhVkROg&e=>
> .
>
-- 

Best Regards,

*Kexin Huang*

New York University
Mobile (USA): +1 917-558-1909
Email: kexin.huang@nyu.edu
