### ISSUE TITLE
Subsampling for class imbalances

### ISSUE THREAD

**Issue by bwang482** [kexinhuang12345/clinicalBERT#12]
Dear Kexin, thanks very much for the great work! 

We are keen to use your approach for our EHR data at hand. May I please ask if you have performed subsampling for balancing the data? If so, have you done so per fold or as a whole before K-fold CV? Any info would be greatly appreciated! 

Thanks again!

**Comment by kexinhuang12345** [comment]
Hi! Yes, during finetuning, I subsample the negative to match the positive patients. I think I did as a whole. But I think per fold would be better to evaluate model robustness!
