### ISSUE TITLE
torch.distributed.init_process_group: setting variables

### ISSUE THREAD

**Issue by bwang482** [kexinhuang12345/clinicalBERT#13]
Hi Kexin, thanks for the repo. I have run into an error executing `run_readmission`:

`python ./run_readmission.py --task_name readmission --readmission_mode early --do_eval --data_dir ./data/3days/ --bert_model ./model/early_readmission --max_seq_length 512 --output_dir ./result_early --local_rank 6`

I am running on a single gpu: 6, and the `n_gpu` is set to be 1 as is already done in your code (though you did use distributed). The error is shown below:

```
in the modeling class
Traceback (most recent call last):
  File "./run_readmission.py", line 705, in <module>
    main()
  File "./run_readmission.py", line 473, in main
    torch.distributed.init_process_group(backend='nccl')
  File "/mnt/sdb/env1/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 423, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/mnt/sdb/env1/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 155, in _env_rendezvous_handler
    raise _env_error("RANK")
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set
```

Surely you have had the same error? Any help would be appreciated! Thanks.

**Comment by kexinhuang12345** [comment]
Hey, I haven't encountered this error before. It seems to turn on the distribution training mode, which we don't want. Maybe just remove --local_rank command, it would not initialize the distribution mode.

**Comment by bwang482** [comment]
Thanks @kexinhuang12345 . I removed the local_rank command and restricted `CUDA_VISIBLE_DEVICES` to only one gpu. Everything looked ok until one error popped up:

```
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 2720/2721 [02:53<00:00, 15.64it/s]
Traceback (most recent call last):
  File "./run_readmission.py", line 705, in <module>
    main()
  File "./run_readmission.py", line 654, in main
    tmp_eval_loss, temp_logits = model(input_ids, segment_ids, input_mask, label_ids)
  File "/mnt/sdb/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/sdb/EHR/clinicalBERT/modeling_readmission.py", line 876, in forward
    loss = loss_fct(n, labels.float())
  File "/mnt/sdb/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/sdb/env1/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 530, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/mnt/sdb/env1/lib/python3.6/site-packages/torch/nn/functional.py", line 2519, in binary_cross_entropy
    "Please ensure they have the same size.".format(target.size(), input.size()))
ValueError: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])) is deprecated. Please ensure they have the same size.
```

**Comment by nischaybikramthapa** [comment]
Hi @kexinhuang12345, Thanks for the repo. I'm having the same issue as @bluemonk482  and wondering if there's any way to resolve this?
![clinical_bert](https://user-images.githubusercontent.com/46451619/112472084-d1524880-8dc0-11eb-8aad-9b7c75ea76c3.JPG)

**Comment by elijah981** [comment]
Hi Kexin, 
It would be great if you tell which version of python is to be used and provide a requirements.txt file as well.
Thanks.

**Comment by kexinhuang12345** [comment]
Hey, sorry for the late reply. Somehow the notification is not turned on for this repo. I don't have the env setup as it is done using HPC at college. But this error is due to size mismatch. In the previous pytorch version, it would automatically match the size, but apparently, this is deprecated.

Can you try in this line: https://github.com/kexinhuang12345/clinicalBERT/blob/3471040c311a86b92cf81acbd0fc4c7ab5c35d22/modeling_readmission.py#L876
Change to 
`loss = loss_fct(n, labels.float().unsqueeze(-1))`

**Comment by CalendulaED** [comment]
Hi @kexinhuang12345 After changing the `loss = loss_fct(n, labels.float()) ` to `loss = loss_fct(n, labels.float().unsqueeze(-1))`
It will show this error:
![image](https://user-images.githubusercontent.com/68514251/117708389-bf284000-b19d-11eb-922a-111ced10d59a.png)
I think the input size is still different, but not sure how to solve this.

**Comment by kexinhuang12345** [comment]
Oh cool, can you do this instead then?

`loss = loss_fct(n.reshape(-1,1), labels.float().reshape(-1,1))`

If it is still not working, can you print(n) and print(labels.float()) and sent the results?

**Comment by CalendulaED** [comment]
Hi @kexinhuang12345 I think after changing it to `loss = loss_fct(n.reshape(-1,1), labels.float().reshape(-1,1))` It works and shows the accuracy.
![image](https://user-images.githubusercontent.com/68514251/117713431-a7ec5100-b1a3-11eb-864e-60535908effe.png)
Is correct for the eval_accuracy and training loss? Since training loss is 100000

**Comment by kexinhuang12345** [comment]
Yeah, as you are using eval mode --do_eval. So as there is no training, it is set to be the default 100000.
