### ISSUE TITLE
Is the Word2Vec model ClinicalBERT?

### ISSUE THREAD

**Issue by sap218** [kexinhuang12345/clinicalBERT#16]
Hi, I'm just checking (towards bottom of README):

> Please use this link to download Word2Vec and FastText models for Clinical Notes.

Does this mean this link directs me to ClinicalBERT as a word2vec model? Thanks! :) 

Just a quick edit: I know the word2vec model won't be ClinicalBERT (as it's a BERT model) - but is it essentially the same?

**Comment by kexinhuang12345** [comment]
Sorry for the super late reply. No they are not the same. The link is for baseline word2vec/fasttext

**Comment by sap218** [comment]
Ah Yes, thank you @kexinhuang12345  - sorry for my previous message, to clarify, I mean: is the same text data used to create the word2vec/fasttext models as the BERT model? (i.e. the same 100,000 clinical letters/preprocessing methods as described in the manuscript)
