### ISSUE TITLE
where is the ADMISSIONS.csv   come from 

### ISSUE THREAD

**Issue by kedimomo** [kexinhuang12345/clinicalBERT#2]
how can I get this csv file  thanks   ，  I can not access the Google Driver   because   china firewall

**Comment by kexinhuang12345** [comment]
Hi, sorry for the late reply. 

The csv files are from the MIMIC3 dataset. https://mimic.physionet.org/about/mimic/

Since it requires the CITI training certificate, I am afraid I couldn't share the dataset with you. But after you obtain the certificate, you can easily download it from the link above. 

The google drive only contains the link to model weights. What driver do you usually use? I can try upload it there. Let me know, thanks!

**Comment by kedimomo** [comment]
@kexinhuang12345   thank you ，reply me this question  ， I have 
see an article you wrote  ，someone translate to chinese  ，A little curious how to work  ， most people use this  cloud driver --》   https://pan.baidu.com/     can provide  1T space to save something

**Comment by kexinhuang12345** [comment]
Can you point to me the Chinese article?

Sure, will try to upload in the upcoming days. Thanks

**Comment by kedimomo** [comment]
My expression may make you misunderstand， so sorry . He just introduced clinicalBERT, but did not translate arxiv's paper. 
https://baike.baidu.com/tashuo/browse/content?id=3e534ed058124746fa5428f0&fr=vipping&qq-pf-to=pcqq.c2c

**Comment by kexinhuang12345** [comment]
Cool thanks for the link! 

To update, the Baidu Pan is updating its registration process for the foreign phone number and they said it will reopen on 7th, I will upload then!

**Comment by kedimomo** [comment]
@kexinhuang12345    thanks

**Comment by kexinhuang12345** [comment]
https://hu-my.sharepoint.com/:u:/g/personal/kexinhuang_hsph_harvard_edu/ERw4LamJD4xNkkONXI7jsiYBUk6QwDv4t3y_jJcrsjkt9A?e=orU3C3

Unfortunately, I couldn't access to the Baidu Pan using a foreign number. So I upload it to a oneDrive server which I heard is not blocked in China. Please try it and let me know if it works, thanks!

**Comment by kedimomo** [comment]
@kexinhuang12345    it work ,  I can download from  this webpage,  thanks

**Comment by kexinhuang12345** [comment]
great! hope it is useful
