### ISSUE TITLE
FastText model

### ISSUE THREAD

**Issue by MaksymDel** [kexinhuang12345/clinicalBERT#5]
Hi, thanks for sharing your work!

However, FastText model is missing in the download folder. Could you please add this one as well?

Also, do you use _cased_ or _uncased_ vocab?

**Comment by kexinhuang12345** [comment]
Hey, just uploaded with a new link! and I use uncased vocab for all the models : )

https://hu-my.sharepoint.com/:u:/g/personal/kexinhuang_hsph_harvard_edu/EcdVZ46f9OZPnFlnFD3jXZgBayNW7T7SrA0lPRf6dlSOzQ?e=sPHF8B
